import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates a professional PDF of job applications
 * @param {Array} jobs - List of job objects to include
 * @param {Object} user - Current user object { name, email }
 */
export const generatePDF = (jobs, user) => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();

  // ── Header ──
  doc.setFontSize(22);
  doc.setTextColor(91, 130, 250); // var(--accent-primary) equivalent
  doc.text('JobPulse', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('Professional Job Application Tracker', 14, 28);
  
  doc.setDrawColor(226, 232, 240); // var(--border-default)
  doc.line(14, 32, 196, 32);

  // ── User Details ──
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59); // slate-800
  doc.setFont('helvetica', 'bold');
  doc.text('Applicant Information', 14, 42);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Name: ${user.name || 'User'}`, 14, 48);
  doc.text(`Email: ${user.email || 'N/A'}`, 14, 53);
  doc.text(`Export Date: ${timestamp}`, 14, 58);
  doc.text(`Total Applications: ${jobs.length}`, 14, 63);

  // ── Table ──
  const tableColumn = ["#", "Company", "Role", "Status", "Date", "Location"];
  const tableRows = [];

  jobs.forEach((job, index) => {
    const jobData = [
      index + 1,
      job.company,
      job.role,
      job.status,
      job.date,
      job.location || 'N/A',
    ];
    tableRows.push(jobData);
  });

  autoTable(doc, {
    startY: 70,
    head: [tableColumn],
    body: tableRows,
    theme: 'striped',
    headStyles: {
      fillColor: [91, 130, 250],
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: 'bold',
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { top: 70 },
  });

  // ── Footer ──
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(
      `Page ${i} of ${pageCount} — Generated by JobPulse`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  const fileName = `JobPulse_Export_${user.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};
